### ISSUE TITLE
Typing in the listbox does not use the font of the listbox

### ISSUE THREAD

**Issue by markuswinter** [Tinrocket-LLC/TRCustomListBox#2]
When I type in the ListBox then the text I type is in a different font and fontsize to the other text in the listbox - should it not take on the font properties at the insertion point?

**Comment by tinrocket** [comment]
It should; I’ve explicity disabled styled text. Can you upload a screenshot?

**Comment by tinrocket** [comment]
@markuswinter  To clarify, in case I misunderstood: TRCustomListBox control can have default font and font size properties that can be overriden by the TRCustomListboxRow objects. Depending on which properties are set, the font used cascades. Some more info on how you’ve configured the rows and control would help me understand the issue better.

**Comment by markuswinter** [comment]
I did not configure anything, I simply ran the demo project and entered some text:

![screenshot_1050](https://github.com/Tinrocket-LLC/TRCustomListBox/assets/880875/6737f022-4607-4503-86e6-f438944f4193)

**Comment by tinrocket** [comment]
Oh wow. The control in question, CellTextArea, has AllowStyledText set to false and isn’t touched anywhere.

What system are you running?

<img width="825" alt="image" src="https://github.com/Tinrocket-LLC/TRCustomListBox/assets/759144/4be71658-f719-41c2-8481-a792d49d6428">

<img width="1179" alt="image" src="https://github.com/Tinrocket-LLC/TRCustomListBox/assets/759144/9620562b-35fc-4b2a-ae64-a43eac97f66d">

**Comment by markuswinter** [comment]
MacOS Mojave 10.14.6

> has AllowStyledText set to false and isn’t touched anywhere.

That might be the problem - try setting the font. StyledText is for formats like bold, underline, etc but may take the default font of the system it is running on.

**Comment by markuswinter** [comment]
Nope - that's not it.

**Comment by markuswinter** [comment]
HA! If I allow styled text then it works as expected.

**Comment by markuswinter** [comment]
It is these two lines that I uncommented:

 ```
Private Sub Update_TextArea(ta as DesktopTextArea, row as TRCustomListBoxRow)

 ta.Text = row.Text
 // ta.FontName = Me.RowFontName(row)
 // ta.FontSize = Me.RowFontSize(row)
 ta.LineHeight = row.LineHeight
 ta.LineSpacing = row.LineSpacing
 ta.TextColor = Me.RowFontColor(row)
 ta.TextAlignment = row.TextAlignment
 ta.MultiLine = row.Multiline
  
End Sub
```

Now all text has the smaller font and is the same as the newly inserted text. 

So the conclusion seems to be you set the font and fontsize here, but not when new text is entered.

**Comment by tinrocket** [comment]
It seems like the meaning of the boolean is reversed on Mojave. That’s strange. I have a machine that has Mojave, but it would take some time to set it up. Which version of XOJO are you running?

**Comment by markuswinter** [comment]
Xojo 2021 R3.1. 

I downloaded the latest version Xojo 2023 R1.1 and it does not show the problem, so it is due to a (fixed) bug in Xojo … 🙄

For users of older versions of Xojo the solution is to enable StyledText (which I prefer anyway).

**Comment by markuswinter** [comment]
Closing the issue …
